_wandb:
    value:
        cli_version: 0.21.3
        e:
            xozauevi7uhgmre88cotijn63szlxiwo:
                codePath: toy_transformer/model.ipynb
                codePathLocal: model.ipynb
                email: ce24b119@smail.iitm.ac.in
                executable: /opt/anaconda3/envs/toytrans/bin/python
                git:
                    commit: cdd0e539ef19f93f2140a667c07378082fe62342
                    remote: https://github.com/ilatims-b/Viveka.git
                host: Smitalis-MacBook-Air.local
                os: macOS-15.2-arm64-arm-64bit
                program: /Users/sbhandari/Documents/GitHub/Vivekafork/toy_transformer/model.ipynb
                python: CPython 3.10.18
                root: /Users/sbhandari/Documents/GitHub/Vivekafork/toy_transformer
                startedAt: "2025-09-13T18:55:45.914371Z"
                writerId: xozauevi7uhgmre88cotijn63szlxiwo
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 71
            "2":
                - 1
                - 11
                - 49
                - 51
                - 71
            "3":
                - 2
            "4": 3.10.18
            "5": 0.21.3
            "6": 4.56.1
            "8":
                - 1
            "10":
                - 20
            "12": 0.21.3
            "13": darwin-arm64
